{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Cryptocurrency Price Action Analysis\n",
    "\n",
    "This notebook demonstrates different approaches to cryptocurrency price prediction:\n",
    "1. Pandas with local processing\n",
    "2. Pandas with Dask distribution\n",
    "3. Full Dask implementation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Imports\n",
    "import matplotlib\n",
    "import matplotlib.pyplot as plt\n",
    "import dask.dataframe as dd\n",
    "import My_API_Wraps\n",
    "import My_FE_Wraps\n",
    "import My_FS_Wraps\n",
    "from dask.distributed import Client, LocalCluster\n",
    "import xgboost\n",
    "from sklearn.metrics import r2_score\n",
    "import pandas as pd\n",
    "import datetime as dt\n",
    "import numpy as np\n",
    "from xgboost import dask as dxgb\n",
    "import os\n",
    "import cupy as cp\n",
    "import optuna\n",
    "import My_ML_Wraps\n",
    "import warnings\n",
    "import coiled\n",
    "import My_Utilities\n",
    "warnings.filterwarnings('ignore')\n",
    "warnings.filterwarnings('ignore', category=DeprecationWarning)\n",
    "warnings.filterwarnings('ignore', category=FutureWarning)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2025-03-02 00:43:09,629][INFO    ][coiled] Fetching latest package priorities...\n",
      "[2025-03-02 00:43:09,632][INFO    ][coiled.package_sync] Resolving your local myenvironment Python environment...\n",
      "[2025-03-02 00:43:10,360][INFO    ][coiled.package_sync] Scanning 146 conda packages...\n",
      "[2025-03-02 00:43:10,370][INFO    ][coiled.package_sync] Scanning 171 python packages...\n",
      "[2025-03-02 00:43:11,531][INFO    ][coiled] Running pip check...\n",
      "[2025-03-02 00:43:12,608][INFO    ][coiled] Validating environment...\n",
      "[2025-03-02 00:43:16,894][INFO    ][coiled] Creating wheel for ~\\AppData\\Roaming\\Python\\Python312\\site-packages\\win32\\lib...\n",
      "[2025-03-02 00:43:17,111][INFO    ][coiled] Creating wheel for ~\\OneDrive\\Desktop\\Programming\\new_programming...\n",
      "[2025-03-02 00:43:17,296][INFO    ][coiled] Creating wheel for ~\\AppData\\Roaming\\Python\\Python312\\site-packages\\pythonwin...\n",
      "[2025-03-02 00:43:17,668][INFO    ][coiled] Creating wheel for ~\\AppData\\Roaming\\Python\\Python312\\site-packages\\win32...\n",
      "[2025-03-02 00:43:18,117][WARNING ][coiled.package_sync] Package - libwinpthread, libwinpthread has no install candidate for Python 3.12 linux-64 on conda-forge\n",
      "[2025-03-02 00:43:18,118][WARNING ][coiled.package_sync] Package - dask-xgboost, Pip check had the following issues that need resolving: \n",
      "dask-xgboost 0.2.0 has requirement xgboost<=0.90, but you have xgboost 2.1.3.\n",
      "[2025-03-02 00:43:18,119][INFO    ][coiled] Uploading coiled_local_lib...\n",
      "[2025-03-02 00:43:19,368][INFO    ][coiled] Uploading coiled_local_new_programming...\n",
      "[2025-03-02 00:43:20,831][INFO    ][coiled] Uploading coiled_local_pythonwin...\n",
      "[2025-03-02 00:43:22,312][INFO    ][coiled] Uploading coiled_local_win32...\n",
      "[2025-03-02 00:43:23,807][INFO    ][coiled] Requesting package sync build...\n",
      "[2025-03-02 00:43:24,909][WARNING ][coiled] Using adaptive scaling with default range of `[4, 20]`. To manually control the size of your cluster, use n_workers=.\n",
      "\n",
      "[2025-03-02 00:43:24,912][INFO    ][coiled] Creating Cluster (name: amalio-hidalgo-7d00f45a, https://cloud.coiled.io/clusters/782559?account=amalio-hidalgo ). This usually takes 1-2 minutes...\n",
      "2025-03-02 00:44:17,625 - distributed.deploy.adaptive_core - INFO - Adaptive scaling started: minimum=4 maximum=20\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "    <div style=\"width: 24px; height: 24px; background-color: #e1e1e1; border: 3px solid #9D9D9D; border-radius: 5px; position: absolute;\"> </div>\n",
       "    <div style=\"margin-left: 48px;\">\n",
       "        <h3 style=\"margin-bottom: 0px;\">Client</h3>\n",
       "        <p style=\"color: #9D9D9D; margin-bottom: 0px;\">Client-174713a0-f6f7-11ef-b510-f020ff5aa2bb</p>\n",
       "        <table style=\"width: 100%; text-align: left;\">\n",
       "\n",
       "        <tr>\n",
       "        \n",
       "            <td style=\"text-align: left;\"><strong>Connection method:</strong> Cluster object</td>\n",
       "            <td style=\"text-align: left;\"><strong>Cluster type:</strong> coiled.Cluster</td>\n",
       "        \n",
       "        </tr>\n",
       "\n",
       "        \n",
       "            <tr>\n",
       "                <td style=\"text-align: left;\">\n",
       "                    <strong>Dashboard: </strong> <a href=\"https://cluster-vpuvq.dask.host/zrNDwLbF5DQirT2C/status\" target=\"_blank\">https://cluster-vpuvq.dask.host/zrNDwLbF5DQirT2C/status</a>\n",
       "                </td>\n",
       "                <td style=\"text-align: left;\"></td>\n",
       "            </tr>\n",
       "        \n",
       "\n",
       "        </table>\n",
       "\n",
       "        \n",
       "\n",
       "        \n",
       "            <details>\n",
       "            <summary style=\"margin-bottom: 20px;\"><h3 style=\"display: inline;\">Cluster Info</h3></summary>\n",
       "            <div class=\"jp-RenderedHTMLCommon jp-RenderedHTML jp-mod-trusted jp-OutputArea-output\">\n",
       "    <div style=\"width: 24px; height: 24px; background-color: #e1e1e1; border: 3px solid #9D9D9D; border-radius: 5px; position: absolute;\">\n",
       "    </div>\n",
       "    <div style=\"margin-left: 48px;\">\n",
       "        <h3 style=\"margin-bottom: 0px; margin-top: 0px;\">Cluster</h3>\n",
       "        <p style=\"color: #9D9D9D; margin-bottom: 0px;\">amalio-hidalgo-7d00f45a</p>\n",
       "        <table style=\"width: 100%; text-align: left;\">\n",
       "            <tr>\n",
       "                <td style=\"text-align: left;\">\n",
       "                    <strong>Dashboard:</strong> <a href=\"https://cluster-vpuvq.dask.host/zrNDwLbF5DQirT2C/status\" target=\"_blank\">https://cluster-vpuvq.dask.host/zrNDwLbF5DQirT2C/status</a>\n",
       "                </td>\n",
       "                <td style=\"text-align: left;\">\n",
       "                    <strong>Workers:</strong> 0\n",
       "                </td>\n",
       "            </tr>\n",
       "            <tr>\n",
       "                <td style=\"text-align: left;\">\n",
       "                    <strong>Total threads:</strong> 0\n",
       "                </td>\n",
       "                <td style=\"text-align: left;\">\n",
       "                    <strong>Total memory:</strong> 0 B\n",
       "                </td>\n",
       "            </tr>\n",
       "            \n",
       "        </table>\n",
       "\n",
       "        <details>\n",
       "            <summary style=\"margin-bottom: 20px;\">\n",
       "                <h3 style=\"display: inline;\">Scheduler Info</h3>\n",
       "            </summary>\n",
       "\n",
       "            <div style=\"\">\n",
       "    <div>\n",
       "        <div style=\"width: 24px; height: 24px; background-color: #FFF7E5; border: 3px solid #FF6132; border-radius: 5px; position: absolute;\"> </div>\n",
       "        <div style=\"margin-left: 48px;\">\n",
       "            <h3 style=\"margin-bottom: 0px;\">Scheduler</h3>\n",
       "            <p style=\"color: #9D9D9D; margin-bottom: 0px;\">Scheduler-d175e969-df3a-4575-bada-8f71f4778a00</p>\n",
       "            <table style=\"width: 100%; text-align: left;\">\n",
       "                <tr>\n",
       "                    <td style=\"text-align: left;\">\n",
       "                        <strong>Comm:</strong> tls://10.0.3.133:8786\n",
       "                    </td>\n",
       "                    <td style=\"text-align: left;\">\n",
       "                        <strong>Workers:</strong> 0\n",
       "                    </td>\n",
       "                </tr>\n",
       "                <tr>\n",
       "                    <td style=\"text-align: left;\">\n",
       "                        <strong>Dashboard:</strong> <a href=\"http://10.0.3.133:8788/status\" target=\"_blank\">http://10.0.3.133:8788/status</a>\n",
       "                    </td>\n",
       "                    <td style=\"text-align: left;\">\n",
       "                        <strong>Total threads:</strong> 0\n",
       "                    </td>\n",
       "                </tr>\n",
       "                <tr>\n",
       "                    <td style=\"text-align: left;\">\n",
       "                        <strong>Started:</strong> Just now\n",
       "                    </td>\n",
       "                    <td style=\"text-align: left;\">\n",
       "                        <strong>Total memory:</strong> 0 B\n",
       "                    </td>\n",
       "                </tr>\n",
       "            </table>\n",
       "        </div>\n",
       "    </div>\n",
       "\n",
       "    <details style=\"margin-left: 48px;\">\n",
       "        <summary style=\"margin-bottom: 20px;\">\n",
       "            <h3 style=\"display: inline;\">Workers</h3>\n",
       "        </summary>\n",
       "\n",
       "        \n",
       "\n",
       "    </details>\n",
       "</div>\n",
       "\n",
       "        </details>\n",
       "    </div>\n",
       "</div>\n",
       "            </details>\n",
       "        \n",
       "\n",
       "    </div>\n",
       "</div>"
      ],
      "text/plain": [
       "<Client: 'tls://10.0.3.133:8786' processes=0 threads=0, memory=0 B>"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Coiled Cluster Connecting to my AWS Account\n",
    "cluster = coiled.Cluster(\n",
    "    # n_workers= 3, # 1 to 3 workers\n",
    "    # worker_memory=\"32GiB\",\n",
    "    region=\"eu-west-3\",\n",
    "    shutdown_on_close=True\n",
    ")\n",
    "client = cluster.get_client()\n",
    "client"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# CPU optimized cluster for my CPU \n",
    "cluster = LocalCluster(\n",
    "            n_workers=4,\n",
    "            threads_per_worker=5,\n",
    "            processes=True,\n",
    "            dashboard_address=':8787',\n",
    "            resources = {'GPU':2}\n",
    "        )\n",
    "client = Client(cluster)\n",
    "client"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Work in progress-GPU optimized cluster with CUDA\n",
    "# Notes:Windows doesn't support dask.distributed.LocalCudaCluster\n",
    "os.environ[\"CUDA_VISIBLE_DEVICES\"] = \"0\"\n",
    "cp.cuda.set_allocator(cp.cuda.MemoryPool().malloc)\n",
    "\n",
    "cluster = LocalCluster(\n",
    "    n_workers=1,              # Single worker for GPU\n",
    "    processes=False,          # Thread-based\n",
    "    threads_per_worker=32,    # Maximum threads for i7-13700H\n",
    "    # memory_limit='22GB',      # 75% of system RAM\n",
    "    dashboard_address=':8788',\n",
    "    resources={'GPU': 1}\n",
    ")\n",
    "client = Client(cluster)\n",
    "client"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Use to close client and cluster when done with Dask computations\n",
    "client.close()\n",
    "cluster.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Key function parameters \n",
    "# Notes: \n",
    "# If timeframe=1, periods are 5minute intervals, else hourly\n",
    "# Max timeframe=89, after lose hourly granularity\n",
    "# For timeframe=1, setting periods higher than 3 will result in inusfficient partition sizes for feature extraction\n",
    "periods= 4\n",
    "timeframe= 89\n",
    "top_coins= 2\n",
    "api_key= \"CG-r57ENE22zzPUiLmjnyFK7YHw\"\n",
    "headers = {\n",
    "    \"accept\": \"application/json\",\n",
    "    \"x-cg-demo-api-key\": api_key\n",
    "    }\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Windows is not officially supported for dask/xgboost, contribution are welcomed.\n"
     ]
    }
   ],
   "source": [
    "# Dask Example- Dask Raw Data, Feature Extraction & Selection, and Train-Test Split\n",
    "# Notes:\n",
    "# Make sure significant features were found by computing some data from X_train/X_test; \n",
    "#   - this code doesnt return an error message like Pandas version\n",
    "future0= client.submit(My_API_Wraps.CoinGecko_HSPD_Dask, timeframe=timeframe, top_coins=top_coins, periods=periods, api_key=api_key)\n",
    "future1= client.submit(My_FE_Wraps.EF_Dask, future0, ParameterComplexity=2, LR=True, Vol=False)\n",
    "future2 = client.submit(My_FS_Wraps.SF_Dask, future1, p_value=0.10)\n",
    "X, y= future2.result()\n",
    "X = X.repartition(npartitions=5)\n",
    "y= y.repartition(npartitions=5)\n",
    "X_train= X.partitions[0:-1]\n",
    "X_test= X.partitions[-1]\n",
    "y_train= y.partitions[0:-1]\n",
    "y_test= y.partitions[-1]\n",
    "X_train, X_test, y_train, y_test = client.persist([X_train, X_test, y_train, y_test])\n",
    "dtrain= dxgb.DaskDMatrix(client, X_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train.compute()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "db6a6f00c3534bc6a0317b8857534f2c",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/500 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Windows is not officially supported for dask/xgboost, contribution are welcomed.\n",
      "Windows is not officially supported for dask/xgboost, contribution are welcomed.\n",
      "Windows is not officially supported for dask/xgboost, contribution are welcomed.\n",
      "Windows is not officially supported for dask/xgboost, contribution are welcomed.\n",
      "Windows is not officially supported for dask/xgboost, contribution are welcomed.\n",
      "Windows is not officially supported for dask/xgboost, contribution are welcomed.\n",
      "Windows is not officially supported for dask/xgboost, contribution are welcomed.\n",
      "Windows is not officially supported for dask/xgboost, contribution are welcomed.\n",
      "Windows is not officially supported for dask/xgboost, contribution are welcomed.\n",
      "Windows is not officially supported for dask/xgboost, contribution are welcomed.\n",
      "Windows is not officially supported for dask/xgboost, contribution are welcomed.\n",
      "Windows is not officially supported for dask/xgboost, contribution are welcomed.\n",
      "Windows is not officially supported for dask/xgboost, contribution are welcomed.\n",
      "Windows is not officially supported for dask/xgboost, contribution are welcomed.\n",
      "Windows is not officially supported for dask/xgboost, contribution are welcomed.\n",
      "Windows is not officially supported for dask/xgboost, contribution are welcomed.\n",
      "Windows is not officially supported for dask/xgboost, contribution are welcomed.\n",
      "Windows is not officially supported for dask/xgboost, contribution are welcomed.\n",
      "Windows is not officially supported for dask/xgboost, contribution are welcomed.\n",
      "Windows is not officially supported for dask/xgboost, contribution are welcomed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[W 2025-03-02 00:53:04,737] Trial 0 failed with parameters: {'lambda': 3.146874023936724, 'alpha': 1.0911045678813782e-06, 'colsample_bytree': 0.9926989065426313, 'max_depth': 15, 'min_child_weight': 1.2126904536901918e-08, 'learning_rate': 2.187693108700852e-06, 'gamma': 0.0028115301905785573} because of the following error: XGBoostError('[23:53:02] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\\nStack trace:\\n  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\\n  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\\n  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\\n  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\\n  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\\n  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\\n  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\\n  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\\n  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\\n\\n').\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py\", line 197, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\OneDrive\\Desktop\\Programming\\new_programming\\My_ML_Wraps.py\", line 139, in objective\n",
      "    output = dxgb.train(\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1090, in train\n",
      "    return client.sync(\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 364, in sync\n",
      "    return sync(\n",
      "           ^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 440, in sync\n",
      "    raise error\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 414, in f\n",
      "    result = yield future\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\amali\\AppData\\Roaming\\Python\\Python312\\site-packages\\tornado\\gen.py\", line 767, in run\n",
      "    value = future.result()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1026, in _train_async\n",
      "    result = await map_worker_partitions(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 551, in map_worker_partitions\n",
      "    result = await client.compute(fut).result()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\client.py\", line 410, in _result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 535, in <lambda>\n",
      "    lambda *args, **kwargs: [func(*args, **kwargs)],\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 990, in dispatched_train\n",
      "    booster = worker_train(\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/training.py\", line 176, in train\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 179, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 374, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 2743, in num_boosted_rounds\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "xgboost.core.XGBoostError: [23:53:02] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\n",
      "Stack trace:\n",
      "  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\n",
      "  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\n",
      "  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\n",
      "  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\n",
      "  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\n",
      "  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\n",
      "  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\n",
      "  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\n",
      "  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\n",
      "\n",
      "\n",
      "[W 2025-03-02 00:53:04,741] Trial 0 failed with value None.\n",
      "[W 2025-03-02 00:53:04,982] Trial 1 failed with parameters: {'lambda': 0.0004200606986444887, 'alpha': 41.53589269457935, 'colsample_bytree': 0.3891976178457907, 'max_depth': 10, 'min_child_weight': 1.3345827742391143e-05, 'learning_rate': 5.465845836899955e-07, 'gamma': 0.05245820774290428} because of the following error: XGBoostError('[23:53:02] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\\nStack trace:\\n  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\\n  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\\n  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\\n  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\\n  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\\n  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\\n  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\\n  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\\n  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\\n\\n').\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py\", line 197, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\OneDrive\\Desktop\\Programming\\new_programming\\My_ML_Wraps.py\", line 139, in objective\n",
      "    output = dxgb.train(\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1090, in train\n",
      "    return client.sync(\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 364, in sync\n",
      "    return sync(\n",
      "           ^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 440, in sync\n",
      "    raise error\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 414, in f\n",
      "    result = yield future\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\amali\\AppData\\Roaming\\Python\\Python312\\site-packages\\tornado\\gen.py\", line 767, in run\n",
      "    value = future.result()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1026, in _train_async\n",
      "    result = await map_worker_partitions(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 551, in map_worker_partitions\n",
      "    result = await client.compute(fut).result()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\client.py\", line 410, in _result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 535, in <lambda>\n",
      "    lambda *args, **kwargs: [func(*args, **kwargs)],\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 990, in dispatched_train\n",
      "    booster = worker_train(\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/training.py\", line 176, in train\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 179, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 374, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 2743, in num_boosted_rounds\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "xgboost.core.XGBoostError: [23:53:02] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\n",
      "Stack trace:\n",
      "  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\n",
      "  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\n",
      "  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\n",
      "  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\n",
      "  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\n",
      "  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\n",
      "  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\n",
      "  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\n",
      "  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\n",
      "\n",
      "\n",
      "[W 2025-03-02 00:53:04,984] Trial 1 failed with value None.\n",
      "[W 2025-03-02 00:53:05,219] Trial 3 failed with parameters: {'lambda': 0.5284907274395373, 'alpha': 0.004914624685831245, 'colsample_bytree': 0.9454262570530594, 'max_depth': 19, 'min_child_weight': 26.2602099403552, 'learning_rate': 1.4216291156274137e-05, 'gamma': 0.07115969530236675} because of the following error: XGBoostError('[23:53:02] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\\nStack trace:\\n  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\\n  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\\n  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\\n  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\\n  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\\n  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\\n  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\\n  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\\n  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\\n\\n').\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py\", line 197, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\OneDrive\\Desktop\\Programming\\new_programming\\My_ML_Wraps.py\", line 139, in objective\n",
      "    output = dxgb.train(\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1090, in train\n",
      "    return client.sync(\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 364, in sync\n",
      "    return sync(\n",
      "           ^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 440, in sync\n",
      "    raise error\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 414, in f\n",
      "    result = yield future\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\amali\\AppData\\Roaming\\Python\\Python312\\site-packages\\tornado\\gen.py\", line 767, in run\n",
      "    value = future.result()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1026, in _train_async\n",
      "    result = await map_worker_partitions(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 551, in map_worker_partitions\n",
      "    result = await client.compute(fut).result()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\client.py\", line 410, in _result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 535, in <lambda>\n",
      "    lambda *args, **kwargs: [func(*args, **kwargs)],\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 990, in dispatched_train\n",
      "    booster = worker_train(\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/training.py\", line 176, in train\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 179, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 374, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 2743, in num_boosted_rounds\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "xgboost.core.XGBoostError: [23:53:02] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\n",
      "Stack trace:\n",
      "  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\n",
      "  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\n",
      "  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\n",
      "  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\n",
      "  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\n",
      "  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\n",
      "  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\n",
      "  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\n",
      "  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\n",
      "\n",
      "\n",
      "[W 2025-03-02 00:53:05,220] Trial 3 failed with value None.\n",
      "[W 2025-03-02 00:53:05,460] Trial 4 failed with parameters: {'lambda': 2.8069288885021143e-06, 'alpha': 6.732902332029062e-05, 'colsample_bytree': 0.7622258916983113, 'max_depth': 18, 'min_child_weight': 43.55064203460059, 'learning_rate': 0.0003783315928753737, 'gamma': 0.0008803608084767296} because of the following error: XGBoostError('[23:53:03] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\\nStack trace:\\n  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\\n  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\\n  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\\n  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\\n  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\\n  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\\n  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\\n  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\\n  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\\n\\n').\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py\", line 197, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\OneDrive\\Desktop\\Programming\\new_programming\\My_ML_Wraps.py\", line 139, in objective\n",
      "    output = dxgb.train(\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1090, in train\n",
      "    return client.sync(\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 364, in sync\n",
      "    return sync(\n",
      "           ^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 440, in sync\n",
      "    raise error\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 414, in f\n",
      "    result = yield future\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\amali\\AppData\\Roaming\\Python\\Python312\\site-packages\\tornado\\gen.py\", line 767, in run\n",
      "    value = future.result()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1026, in _train_async\n",
      "    result = await map_worker_partitions(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 551, in map_worker_partitions\n",
      "    result = await client.compute(fut).result()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\client.py\", line 410, in _result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 535, in <lambda>\n",
      "    lambda *args, **kwargs: [func(*args, **kwargs)],\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 990, in dispatched_train\n",
      "    booster = worker_train(\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/training.py\", line 176, in train\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 179, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 374, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 2743, in num_boosted_rounds\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "xgboost.core.XGBoostError: [23:53:03] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\n",
      "Stack trace:\n",
      "  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\n",
      "  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\n",
      "  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\n",
      "  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\n",
      "  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\n",
      "  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\n",
      "  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\n",
      "  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\n",
      "  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\n",
      "\n",
      "\n",
      "[W 2025-03-02 00:53:05,461] Trial 4 failed with value None.\n",
      "[W 2025-03-02 00:53:05,701] Trial 10 failed with parameters: {'lambda': 0.04025299426687504, 'alpha': 3.492039008011867e-07, 'colsample_bytree': 0.7227659220820668, 'max_depth': 2, 'min_child_weight': 2.0440115938894848e-07, 'learning_rate': 0.0020417568097816146, 'gamma': 1.1113303557539912e-06} because of the following error: XGBoostError('[23:53:03] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\\nStack trace:\\n  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\\n  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\\n  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\\n  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\\n  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\\n  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\\n  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\\n  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\\n  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\\n\\n').\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py\", line 197, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\OneDrive\\Desktop\\Programming\\new_programming\\My_ML_Wraps.py\", line 139, in objective\n",
      "    output = dxgb.train(\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1090, in train\n",
      "    return client.sync(\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 364, in sync\n",
      "    return sync(\n",
      "           ^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 440, in sync\n",
      "    raise error\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 414, in f\n",
      "    result = yield future\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\amali\\AppData\\Roaming\\Python\\Python312\\site-packages\\tornado\\gen.py\", line 767, in run\n",
      "    value = future.result()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1026, in _train_async\n",
      "    result = await map_worker_partitions(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 551, in map_worker_partitions\n",
      "    result = await client.compute(fut).result()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\client.py\", line 410, in _result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 535, in <lambda>\n",
      "    lambda *args, **kwargs: [func(*args, **kwargs)],\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 990, in dispatched_train\n",
      "    booster = worker_train(\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/training.py\", line 176, in train\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 179, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 374, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 2743, in num_boosted_rounds\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "xgboost.core.XGBoostError: [23:53:03] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\n",
      "Stack trace:\n",
      "  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\n",
      "  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\n",
      "  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\n",
      "  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\n",
      "  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\n",
      "  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\n",
      "  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\n",
      "  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\n",
      "  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\n",
      "\n",
      "\n",
      "[W 2025-03-02 00:53:05,704] Trial 10 failed with value None.\n",
      "[W 2025-03-02 00:53:05,981] Trial 5 failed with parameters: {'lambda': 32.98294630866299, 'alpha': 88.85333987562154, 'colsample_bytree': 0.3339224388497709, 'max_depth': 19, 'min_child_weight': 0.07051869408559679, 'learning_rate': 5.515714640796904e-06, 'gamma': 2.9166957698443084e-08} because of the following error: XGBoostError('[23:53:03] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\\nStack trace:\\n  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\\n  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\\n  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\\n  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\\n  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\\n  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\\n  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\\n  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\\n  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\\n\\n').\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py\", line 197, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\OneDrive\\Desktop\\Programming\\new_programming\\My_ML_Wraps.py\", line 139, in objective\n",
      "    output = dxgb.train(\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1090, in train\n",
      "    return client.sync(\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 364, in sync\n",
      "    return sync(\n",
      "           ^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 440, in sync\n",
      "    raise error\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 414, in f\n",
      "    result = yield future\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\amali\\AppData\\Roaming\\Python\\Python312\\site-packages\\tornado\\gen.py\", line 767, in run\n",
      "    value = future.result()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1026, in _train_async\n",
      "    result = await map_worker_partitions(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 551, in map_worker_partitions\n",
      "    result = await client.compute(fut).result()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\client.py\", line 410, in _result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 535, in <lambda>\n",
      "    lambda *args, **kwargs: [func(*args, **kwargs)],\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 990, in dispatched_train\n",
      "    booster = worker_train(\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/training.py\", line 176, in train\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 179, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 374, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 2743, in num_boosted_rounds\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "xgboost.core.XGBoostError: [23:53:03] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\n",
      "Stack trace:\n",
      "  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\n",
      "  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\n",
      "  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\n",
      "  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\n",
      "  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\n",
      "  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\n",
      "  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\n",
      "  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\n",
      "  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\n",
      "\n",
      "\n",
      "[W 2025-03-02 00:53:05,984] Trial 5 failed with value None.\n",
      "[W 2025-03-02 00:53:06,229] Trial 2 failed with parameters: {'lambda': 2.2835473344481847e-07, 'alpha': 1.3620432784563414e-07, 'colsample_bytree': 0.6132619563625825, 'max_depth': 15, 'min_child_weight': 3.542111137320384e-06, 'learning_rate': 2.4085217102386098e-05, 'gamma': 0.5080434861875956} because of the following error: XGBoostError('[23:53:03] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\\nStack trace:\\n  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\\n  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\\n  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\\n  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\\n  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\\n  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\\n  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\\n  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\\n  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\\n\\n').\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py\", line 197, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\OneDrive\\Desktop\\Programming\\new_programming\\My_ML_Wraps.py\", line 139, in objective\n",
      "    output = dxgb.train(\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1090, in train\n",
      "    return client.sync(\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 364, in sync\n",
      "    return sync(\n",
      "           ^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 440, in sync\n",
      "    raise error\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 414, in f\n",
      "    result = yield future\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\amali\\AppData\\Roaming\\Python\\Python312\\site-packages\\tornado\\gen.py\", line 767, in run\n",
      "    value = future.result()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1026, in _train_async\n",
      "    result = await map_worker_partitions(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 551, in map_worker_partitions\n",
      "    result = await client.compute(fut).result()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\client.py\", line 410, in _result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 535, in <lambda>\n",
      "    lambda *args, **kwargs: [func(*args, **kwargs)],\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 990, in dispatched_train\n",
      "    booster = worker_train(\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/training.py\", line 176, in train\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 179, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 374, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 2743, in num_boosted_rounds\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "xgboost.core.XGBoostError: [23:53:03] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\n",
      "Stack trace:\n",
      "  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\n",
      "  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\n",
      "  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\n",
      "  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\n",
      "  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\n",
      "  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\n",
      "  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\n",
      "  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\n",
      "  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\n",
      "\n",
      "\n",
      "[W 2025-03-02 00:53:06,233] Trial 2 failed with value None.\n",
      "[W 2025-03-02 00:53:06,469] Trial 7 failed with parameters: {'lambda': 2.5710494950858777e-05, 'alpha': 0.006656008731791402, 'colsample_bytree': 0.37745131428539413, 'max_depth': 8, 'min_child_weight': 3.2242297965927343e-07, 'learning_rate': 0.012452911907746242, 'gamma': 8.66878875122016e-05} because of the following error: XGBoostError('[23:53:04] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\\nStack trace:\\n  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\\n  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\\n  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\\n  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\\n  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\\n  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\\n  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\\n  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\\n  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\\n\\n').\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py\", line 197, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\OneDrive\\Desktop\\Programming\\new_programming\\My_ML_Wraps.py\", line 139, in objective\n",
      "    output = dxgb.train(\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1090, in train\n",
      "    return client.sync(\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 364, in sync\n",
      "    return sync(\n",
      "           ^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 440, in sync\n",
      "    raise error\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 414, in f\n",
      "    result = yield future\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\amali\\AppData\\Roaming\\Python\\Python312\\site-packages\\tornado\\gen.py\", line 767, in run\n",
      "    value = future.result()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1026, in _train_async\n",
      "    result = await map_worker_partitions(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 551, in map_worker_partitions\n",
      "    result = await client.compute(fut).result()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\client.py\", line 410, in _result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 535, in <lambda>\n",
      "    lambda *args, **kwargs: [func(*args, **kwargs)],\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 990, in dispatched_train\n",
      "    booster = worker_train(\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/training.py\", line 176, in train\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 179, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 374, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 2743, in num_boosted_rounds\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "xgboost.core.XGBoostError: [23:53:04] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\n",
      "Stack trace:\n",
      "  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\n",
      "  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\n",
      "  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\n",
      "  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\n",
      "  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\n",
      "  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\n",
      "  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\n",
      "  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\n",
      "  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\n",
      "\n",
      "\n",
      "[W 2025-03-02 00:53:06,470] Trial 7 failed with value None.\n",
      "[W 2025-03-02 00:53:06,709] Trial 14 failed with parameters: {'lambda': 0.00027469193473045675, 'alpha': 9.486822775633538, 'colsample_bytree': 0.6693404331390811, 'max_depth': 10, 'min_child_weight': 0.001628518183174638, 'learning_rate': 5.21532205762232e-05, 'gamma': 0.0024587527391458754} because of the following error: XGBoostError('[23:53:04] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\\nStack trace:\\n  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\\n  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\\n  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\\n  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\\n  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\\n  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\\n  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\\n  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\\n  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\\n\\n').\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py\", line 197, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\OneDrive\\Desktop\\Programming\\new_programming\\My_ML_Wraps.py\", line 139, in objective\n",
      "    output = dxgb.train(\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1090, in train\n",
      "    return client.sync(\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 364, in sync\n",
      "    return sync(\n",
      "           ^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 440, in sync\n",
      "    raise error\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 414, in f\n",
      "    result = yield future\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\amali\\AppData\\Roaming\\Python\\Python312\\site-packages\\tornado\\gen.py\", line 767, in run\n",
      "    value = future.result()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1026, in _train_async\n",
      "    result = await map_worker_partitions(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 551, in map_worker_partitions\n",
      "    result = await client.compute(fut).result()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\client.py\", line 410, in _result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 535, in <lambda>\n",
      "    lambda *args, **kwargs: [func(*args, **kwargs)],\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 990, in dispatched_train\n",
      "    booster = worker_train(\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/training.py\", line 176, in train\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 179, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 374, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 2743, in num_boosted_rounds\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "xgboost.core.XGBoostError: [23:53:04] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\n",
      "Stack trace:\n",
      "  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\n",
      "  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\n",
      "  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\n",
      "  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\n",
      "  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\n",
      "  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\n",
      "  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\n",
      "  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\n",
      "  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\n",
      "\n",
      "\n",
      "[W 2025-03-02 00:53:06,710] Trial 14 failed with value None.\n",
      "[W 2025-03-02 00:53:06,955] Trial 6 failed with parameters: {'lambda': 7.54710991140376e-05, 'alpha': 6.743150357163405e-07, 'colsample_bytree': 0.7663054058469443, 'max_depth': 3, 'min_child_weight': 4.5132545183337755e-08, 'learning_rate': 0.004805511242235432, 'gamma': 3.008710196379042e-06} because of the following error: XGBoostError('[23:53:04] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\\nStack trace:\\n  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\\n  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\\n  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\\n  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\\n  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\\n  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\\n  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\\n  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\\n  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\\n\\n').\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py\", line 197, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\OneDrive\\Desktop\\Programming\\new_programming\\My_ML_Wraps.py\", line 139, in objective\n",
      "    output = dxgb.train(\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1090, in train\n",
      "    return client.sync(\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 364, in sync\n",
      "    return sync(\n",
      "           ^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 440, in sync\n",
      "    raise error\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 414, in f\n",
      "    result = yield future\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\amali\\AppData\\Roaming\\Python\\Python312\\site-packages\\tornado\\gen.py\", line 767, in run\n",
      "    value = future.result()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1026, in _train_async\n",
      "    result = await map_worker_partitions(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 551, in map_worker_partitions\n",
      "    result = await client.compute(fut).result()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\client.py\", line 410, in _result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 535, in <lambda>\n",
      "    lambda *args, **kwargs: [func(*args, **kwargs)],\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 990, in dispatched_train\n",
      "    booster = worker_train(\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/training.py\", line 176, in train\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 179, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 374, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 2743, in num_boosted_rounds\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "xgboost.core.XGBoostError: [23:53:04] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\n",
      "Stack trace:\n",
      "  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\n",
      "  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\n",
      "  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\n",
      "  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\n",
      "  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\n",
      "  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\n",
      "  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\n",
      "  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\n",
      "  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\n",
      "\n",
      "\n",
      "[W 2025-03-02 00:53:06,958] Trial 6 failed with value None.\n",
      "[W 2025-03-02 00:53:07,203] Trial 9 failed with parameters: {'lambda': 1.1320589652489047e-05, 'alpha': 0.54378947667069, 'colsample_bytree': 0.3770971349593425, 'max_depth': 9, 'min_child_weight': 3.6731321391492084, 'learning_rate': 0.09919867881162613, 'gamma': 0.002087041029780932} because of the following error: XGBoostError('[23:53:04] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\\nStack trace:\\n  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\\n  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\\n  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\\n  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\\n  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\\n  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\\n  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\\n  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\\n  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\\n\\n').\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py\", line 197, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\OneDrive\\Desktop\\Programming\\new_programming\\My_ML_Wraps.py\", line 139, in objective\n",
      "    output = dxgb.train(\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1090, in train\n",
      "    return client.sync(\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 364, in sync\n",
      "    return sync(\n",
      "           ^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 440, in sync\n",
      "    raise error\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 414, in f\n",
      "    result = yield future\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\amali\\AppData\\Roaming\\Python\\Python312\\site-packages\\tornado\\gen.py\", line 767, in run\n",
      "    value = future.result()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1026, in _train_async\n",
      "    result = await map_worker_partitions(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 551, in map_worker_partitions\n",
      "    result = await client.compute(fut).result()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\client.py\", line 410, in _result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 535, in <lambda>\n",
      "    lambda *args, **kwargs: [func(*args, **kwargs)],\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 990, in dispatched_train\n",
      "    booster = worker_train(\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/training.py\", line 176, in train\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 179, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 374, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 2743, in num_boosted_rounds\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "xgboost.core.XGBoostError: [23:53:04] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\n",
      "Stack trace:\n",
      "  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\n",
      "  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\n",
      "  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\n",
      "  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\n",
      "  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\n",
      "  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\n",
      "  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\n",
      "  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\n",
      "  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\n",
      "\n",
      "\n",
      "[W 2025-03-02 00:53:07,206] Trial 9 failed with value None.\n",
      "[W 2025-03-02 00:53:07,452] Trial 13 failed with parameters: {'lambda': 0.01190269190299359, 'alpha': 1.2971063925187054e-07, 'colsample_bytree': 0.23589703183313004, 'max_depth': 12, 'min_child_weight': 7.841774053821866e-08, 'learning_rate': 1.0685289632503243e-05, 'gamma': 9.157125011506408e-08} because of the following error: XGBoostError('[23:53:05] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\\nStack trace:\\n  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\\n  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\\n  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\\n  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\\n  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\\n  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\\n  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\\n  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\\n  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\\n\\n').\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py\", line 197, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\OneDrive\\Desktop\\Programming\\new_programming\\My_ML_Wraps.py\", line 139, in objective\n",
      "    output = dxgb.train(\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1090, in train\n",
      "    return client.sync(\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 364, in sync\n",
      "    return sync(\n",
      "           ^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 440, in sync\n",
      "    raise error\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 414, in f\n",
      "    result = yield future\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\amali\\AppData\\Roaming\\Python\\Python312\\site-packages\\tornado\\gen.py\", line 767, in run\n",
      "    value = future.result()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1026, in _train_async\n",
      "    result = await map_worker_partitions(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 551, in map_worker_partitions\n",
      "    result = await client.compute(fut).result()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\client.py\", line 410, in _result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 535, in <lambda>\n",
      "    lambda *args, **kwargs: [func(*args, **kwargs)],\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 990, in dispatched_train\n",
      "    booster = worker_train(\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/training.py\", line 176, in train\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 179, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 374, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 2743, in num_boosted_rounds\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "xgboost.core.XGBoostError: [23:53:05] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\n",
      "Stack trace:\n",
      "  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\n",
      "  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\n",
      "  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\n",
      "  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\n",
      "  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\n",
      "  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\n",
      "  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\n",
      "  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\n",
      "  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\n",
      "\n",
      "\n",
      "[W 2025-03-02 00:53:07,453] Trial 13 failed with value None.\n",
      "[W 2025-03-02 00:53:07,719] Trial 11 failed with parameters: {'lambda': 0.15917182451588255, 'alpha': 1.1169141216461542, 'colsample_bytree': 0.235633988377605, 'max_depth': 16, 'min_child_weight': 28.342072666650594, 'learning_rate': 1.707931419284612e-07, 'gamma': 0.1707669948103211} because of the following error: XGBoostError('[23:53:05] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\\nStack trace:\\n  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\\n  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\\n  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\\n  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\\n  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\\n  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\\n  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\\n  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\\n  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\\n\\n').\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py\", line 197, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\OneDrive\\Desktop\\Programming\\new_programming\\My_ML_Wraps.py\", line 139, in objective\n",
      "    output = dxgb.train(\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1090, in train\n",
      "    return client.sync(\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 364, in sync\n",
      "    return sync(\n",
      "           ^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 440, in sync\n",
      "    raise error\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 414, in f\n",
      "    result = yield future\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\amali\\AppData\\Roaming\\Python\\Python312\\site-packages\\tornado\\gen.py\", line 767, in run\n",
      "    value = future.result()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1026, in _train_async\n",
      "    result = await map_worker_partitions(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 551, in map_worker_partitions\n",
      "    result = await client.compute(fut).result()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\client.py\", line 410, in _result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 535, in <lambda>\n",
      "    lambda *args, **kwargs: [func(*args, **kwargs)],\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 990, in dispatched_train\n",
      "    booster = worker_train(\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/training.py\", line 176, in train\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 179, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 374, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 2743, in num_boosted_rounds\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "xgboost.core.XGBoostError: [23:53:05] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\n",
      "Stack trace:\n",
      "  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\n",
      "  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\n",
      "  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\n",
      "  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\n",
      "  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\n",
      "  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\n",
      "  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\n",
      "  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\n",
      "  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\n",
      "\n",
      "\n",
      "[W 2025-03-02 00:53:07,721] Trial 11 failed with value None.\n",
      "[W 2025-03-02 00:53:07,975] Trial 8 failed with parameters: {'lambda': 1.7805394983675726, 'alpha': 0.00018406460192999346, 'colsample_bytree': 0.46579299383930906, 'max_depth': 7, 'min_child_weight': 15.400961467145159, 'learning_rate': 0.2414201495133848, 'gamma': 0.00026569735411860533} because of the following error: XGBoostError('[23:53:05] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\\nStack trace:\\n  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\\n  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\\n  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\\n  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\\n  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\\n  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\\n  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\\n  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\\n  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\\n\\n').\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py\", line 197, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\OneDrive\\Desktop\\Programming\\new_programming\\My_ML_Wraps.py\", line 139, in objective\n",
      "    output = dxgb.train(\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1090, in train\n",
      "    return client.sync(\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 364, in sync\n",
      "    return sync(\n",
      "           ^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 440, in sync\n",
      "    raise error\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 414, in f\n",
      "    result = yield future\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\amali\\AppData\\Roaming\\Python\\Python312\\site-packages\\tornado\\gen.py\", line 767, in run\n",
      "    value = future.result()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1026, in _train_async\n",
      "    result = await map_worker_partitions(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 551, in map_worker_partitions\n",
      "    result = await client.compute(fut).result()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\client.py\", line 410, in _result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 535, in <lambda>\n",
      "    lambda *args, **kwargs: [func(*args, **kwargs)],\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 990, in dispatched_train\n",
      "    booster = worker_train(\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/training.py\", line 176, in train\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 179, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 374, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 2743, in num_boosted_rounds\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "xgboost.core.XGBoostError: [23:53:05] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\n",
      "Stack trace:\n",
      "  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\n",
      "  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\n",
      "  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\n",
      "  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\n",
      "  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\n",
      "  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\n",
      "  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\n",
      "  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\n",
      "  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\n",
      "\n",
      "\n",
      "[W 2025-03-02 00:53:07,978] Trial 8 failed with value None.\n",
      "[W 2025-03-02 00:53:08,214] Trial 15 failed with parameters: {'lambda': 0.2657426413201385, 'alpha': 0.03639538264541166, 'colsample_bytree': 0.286694325932112, 'max_depth': 9, 'min_child_weight': 1.3588495542756878e-07, 'learning_rate': 4.5094976516054683e-07, 'gamma': 1.381584110613968e-06} because of the following error: XGBoostError('[23:53:05] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\\nStack trace:\\n  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\\n  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\\n  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\\n  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\\n  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\\n  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\\n  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\\n  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\\n  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\\n\\n').\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py\", line 197, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\OneDrive\\Desktop\\Programming\\new_programming\\My_ML_Wraps.py\", line 139, in objective\n",
      "    output = dxgb.train(\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1090, in train\n",
      "    return client.sync(\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 364, in sync\n",
      "    return sync(\n",
      "           ^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 440, in sync\n",
      "    raise error\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 414, in f\n",
      "    result = yield future\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\amali\\AppData\\Roaming\\Python\\Python312\\site-packages\\tornado\\gen.py\", line 767, in run\n",
      "    value = future.result()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1026, in _train_async\n",
      "    result = await map_worker_partitions(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 551, in map_worker_partitions\n",
      "    result = await client.compute(fut).result()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\client.py\", line 410, in _result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 535, in <lambda>\n",
      "    lambda *args, **kwargs: [func(*args, **kwargs)],\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 990, in dispatched_train\n",
      "    booster = worker_train(\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/training.py\", line 176, in train\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 179, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 374, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 2743, in num_boosted_rounds\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "xgboost.core.XGBoostError: [23:53:05] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\n",
      "Stack trace:\n",
      "  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\n",
      "  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\n",
      "  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\n",
      "  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\n",
      "  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\n",
      "  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\n",
      "  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\n",
      "  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\n",
      "  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\n",
      "\n",
      "\n",
      "[W 2025-03-02 00:53:08,215] Trial 15 failed with value None.\n",
      "[W 2025-03-02 00:53:08,473] Trial 17 failed with parameters: {'lambda': 0.19938169494456068, 'alpha': 0.0005270751213559993, 'colsample_bytree': 0.6471225896280145, 'max_depth': 6, 'min_child_weight': 0.02256684083423545, 'learning_rate': 4.940875985531728e-06, 'gamma': 0.008378369960388776} because of the following error: XGBoostError('[23:53:06] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\\nStack trace:\\n  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\\n  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\\n  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\\n  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\\n  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\\n  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\\n  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\\n  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\\n  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\\n\\n').\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py\", line 197, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\OneDrive\\Desktop\\Programming\\new_programming\\My_ML_Wraps.py\", line 139, in objective\n",
      "    output = dxgb.train(\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1090, in train\n",
      "    return client.sync(\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 364, in sync\n",
      "    return sync(\n",
      "           ^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 440, in sync\n",
      "    raise error\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 414, in f\n",
      "    result = yield future\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\amali\\AppData\\Roaming\\Python\\Python312\\site-packages\\tornado\\gen.py\", line 767, in run\n",
      "    value = future.result()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1026, in _train_async\n",
      "    result = await map_worker_partitions(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 551, in map_worker_partitions\n",
      "    result = await client.compute(fut).result()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\client.py\", line 410, in _result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 535, in <lambda>\n",
      "    lambda *args, **kwargs: [func(*args, **kwargs)],\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 990, in dispatched_train\n",
      "    booster = worker_train(\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/training.py\", line 176, in train\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 179, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 374, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 2743, in num_boosted_rounds\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "xgboost.core.XGBoostError: [23:53:06] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\n",
      "Stack trace:\n",
      "  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\n",
      "  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\n",
      "  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\n",
      "  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\n",
      "  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\n",
      "  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\n",
      "  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\n",
      "  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\n",
      "  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\n",
      "\n",
      "\n",
      "[W 2025-03-02 00:53:08,475] Trial 17 failed with value None.\n",
      "[W 2025-03-02 00:53:08,723] Trial 16 failed with parameters: {'lambda': 41.65676812607064, 'alpha': 4.97827488982739e-06, 'colsample_bytree': 0.39991607680137903, 'max_depth': 5, 'min_child_weight': 6.747832785813411e-05, 'learning_rate': 2.1185485252363924e-08, 'gamma': 0.1391121118417413} because of the following error: XGBoostError('[23:53:06] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\\nStack trace:\\n  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\\n  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\\n  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\\n  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\\n  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\\n  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\\n  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\\n  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\\n  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\\n\\n').\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py\", line 197, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\OneDrive\\Desktop\\Programming\\new_programming\\My_ML_Wraps.py\", line 139, in objective\n",
      "    output = dxgb.train(\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1090, in train\n",
      "    return client.sync(\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 364, in sync\n",
      "    return sync(\n",
      "           ^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 440, in sync\n",
      "    raise error\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 414, in f\n",
      "    result = yield future\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\amali\\AppData\\Roaming\\Python\\Python312\\site-packages\\tornado\\gen.py\", line 767, in run\n",
      "    value = future.result()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1026, in _train_async\n",
      "    result = await map_worker_partitions(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 551, in map_worker_partitions\n",
      "    result = await client.compute(fut).result()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\client.py\", line 410, in _result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 535, in <lambda>\n",
      "    lambda *args, **kwargs: [func(*args, **kwargs)],\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 990, in dispatched_train\n",
      "    booster = worker_train(\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/training.py\", line 176, in train\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 179, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 374, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 2743, in num_boosted_rounds\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "xgboost.core.XGBoostError: [23:53:06] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\n",
      "Stack trace:\n",
      "  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\n",
      "  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\n",
      "  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\n",
      "  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\n",
      "  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\n",
      "  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\n",
      "  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\n",
      "  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\n",
      "  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\n",
      "\n",
      "\n",
      "[W 2025-03-02 00:53:08,726] Trial 16 failed with value None.\n",
      "[W 2025-03-02 00:53:08,972] Trial 19 failed with parameters: {'lambda': 0.1839933702015765, 'alpha': 6.536541190043145e-07, 'colsample_bytree': 0.3148700607769677, 'max_depth': 18, 'min_child_weight': 0.024525628334110712, 'learning_rate': 2.559936035312511e-05, 'gamma': 1.529679386264567e-08} because of the following error: XGBoostError('[23:53:06] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\\nStack trace:\\n  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\\n  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\\n  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\\n  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\\n  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\\n  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\\n  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\\n  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\\n  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\\n\\n').\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py\", line 197, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\OneDrive\\Desktop\\Programming\\new_programming\\My_ML_Wraps.py\", line 139, in objective\n",
      "    output = dxgb.train(\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1090, in train\n",
      "    return client.sync(\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 364, in sync\n",
      "    return sync(\n",
      "           ^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 440, in sync\n",
      "    raise error\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 414, in f\n",
      "    result = yield future\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\amali\\AppData\\Roaming\\Python\\Python312\\site-packages\\tornado\\gen.py\", line 767, in run\n",
      "    value = future.result()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1026, in _train_async\n",
      "    result = await map_worker_partitions(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 551, in map_worker_partitions\n",
      "    result = await client.compute(fut).result()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\client.py\", line 410, in _result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 535, in <lambda>\n",
      "    lambda *args, **kwargs: [func(*args, **kwargs)],\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 990, in dispatched_train\n",
      "    booster = worker_train(\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/training.py\", line 176, in train\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 179, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 374, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 2743, in num_boosted_rounds\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "xgboost.core.XGBoostError: [23:53:06] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\n",
      "Stack trace:\n",
      "  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\n",
      "  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\n",
      "  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\n",
      "  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\n",
      "  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\n",
      "  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\n",
      "  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\n",
      "  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\n",
      "  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\n",
      "\n",
      "\n",
      "[W 2025-03-02 00:53:08,974] Trial 19 failed with value None.\n",
      "[W 2025-03-02 00:53:09,235] Trial 12 failed with parameters: {'lambda': 4.876149224079619e-08, 'alpha': 4.336607552847569e-08, 'colsample_bytree': 0.7908729837381985, 'max_depth': 2, 'min_child_weight': 0.008162684486355612, 'learning_rate': 1.0090456536683576e-05, 'gamma': 0.037525494266852776} because of the following error: XGBoostError('[23:53:06] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\\nStack trace:\\n  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\\n  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\\n  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\\n  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\\n  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\\n  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\\n  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\\n  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\\n  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\\n\\n').\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py\", line 197, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\OneDrive\\Desktop\\Programming\\new_programming\\My_ML_Wraps.py\", line 139, in objective\n",
      "    output = dxgb.train(\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1090, in train\n",
      "    return client.sync(\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 364, in sync\n",
      "    return sync(\n",
      "           ^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 440, in sync\n",
      "    raise error\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 414, in f\n",
      "    result = yield future\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\amali\\AppData\\Roaming\\Python\\Python312\\site-packages\\tornado\\gen.py\", line 767, in run\n",
      "    value = future.result()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1026, in _train_async\n",
      "    result = await map_worker_partitions(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 551, in map_worker_partitions\n",
      "    result = await client.compute(fut).result()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\client.py\", line 410, in _result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 535, in <lambda>\n",
      "    lambda *args, **kwargs: [func(*args, **kwargs)],\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 990, in dispatched_train\n",
      "    booster = worker_train(\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/training.py\", line 176, in train\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 179, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 374, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 2743, in num_boosted_rounds\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "xgboost.core.XGBoostError: [23:53:06] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\n",
      "Stack trace:\n",
      "  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\n",
      "  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\n",
      "  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\n",
      "  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\n",
      "  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\n",
      "  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\n",
      "  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\n",
      "  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\n",
      "  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\n",
      "\n",
      "\n",
      "[W 2025-03-02 00:53:09,238] Trial 12 failed with value None.\n",
      "[W 2025-03-02 00:53:09,444] Trial 18 failed with parameters: {'lambda': 0.0006599972467084598, 'alpha': 2.3485212673889665e-08, 'colsample_bytree': 0.7648209081612056, 'max_depth': 15, 'min_child_weight': 0.0005478939432983619, 'learning_rate': 0.011422649791820035, 'gamma': 0.00011508016672702738} because of the following error: XGBoostError('[23:53:07] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\\nStack trace:\\n  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\\n  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\\n  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\\n  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\\n  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\\n  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\\n  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\\n  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\\n  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\\n\\n').\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py\", line 197, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\OneDrive\\Desktop\\Programming\\new_programming\\My_ML_Wraps.py\", line 139, in objective\n",
      "    output = dxgb.train(\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1090, in train\n",
      "    return client.sync(\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 364, in sync\n",
      "    return sync(\n",
      "           ^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 440, in sync\n",
      "    raise error\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py\", line 414, in f\n",
      "    result = yield future\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\amali\\AppData\\Roaming\\Python\\Python312\\site-packages\\tornado\\gen.py\", line 767, in run\n",
      "    value = future.result()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 1026, in _train_async\n",
      "    result = await map_worker_partitions(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 551, in map_worker_partitions\n",
      "    result = await client.compute(fut).result()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\client.py\", line 410, in _result\n",
      "    raise exc.with_traceback(tb)\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 535, in <lambda>\n",
      "    lambda *args, **kwargs: [func(*args, **kwargs)],\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py\", line 990, in dispatched_train\n",
      "    booster = worker_train(\n",
      "    ^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/training.py\", line 176, in train\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 179, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py\", line 374, in before_training\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 2743, in num_boosted_rounds\n",
      "  File \"/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "xgboost.core.XGBoostError: [23:53:07] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\n",
      "Stack trace:\n",
      "  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\n",
      "  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\n",
      "  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\n",
      "  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\n",
      "  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\n",
      "  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\n",
      "  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\n",
      "  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\n",
      "  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\n",
      "\n",
      "\n",
      "[W 2025-03-02 00:53:09,447] Trial 18 failed with value None.\n"
     ]
    },
    {
     "ename": "XGBoostError",
     "evalue": "[23:53:02] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\nStack trace:\n  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\n  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\n  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\n  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\n  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\n  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\n  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\n  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\n  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\n\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mXGBoostError\u001b[0m                              Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[5], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;66;03m# Dask Example:Optuna Hyperparameter Optimization and Model Training\u001b[39;00m\n\u001b[1;32m----> 2\u001b[0m study\u001b[38;5;241m=\u001b[39m \u001b[43mMy_ML_Wraps\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mOptuna_XGB_Dask\u001b[49m\u001b[43m(\u001b[49m\u001b[43mclient\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mdtrain\u001b[49m\u001b[43m,\u001b[49m\u001b[43m  \u001b[49m\u001b[43mn_trials\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m500\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mn_rounds\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m100\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43meval_metric\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m \u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mmape\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtree_method\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mhist\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mearly_stopping_rounds\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m20\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[0;32m      3\u001b[0m final_model\u001b[38;5;241m=\u001b[39m dxgb\u001b[38;5;241m.\u001b[39mtrain(client, study\u001b[38;5;241m.\u001b[39mbest_params, dtrain, num_boost_round\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m100\u001b[39m, evals\u001b[38;5;241m=\u001b[39m[(dtrain, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtrain\u001b[39m\u001b[38;5;124m\"\u001b[39m)])\n\u001b[0;32m      4\u001b[0m model_features \u001b[38;5;241m=\u001b[39m final_model[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mbooster\u001b[39m\u001b[38;5;124m'\u001b[39m]\u001b[38;5;241m.\u001b[39mfeature_names\n",
      "File \u001b[1;32mc:\\Users\\amali\\OneDrive\\Desktop\\Programming\\new_programming\\My_ML_Wraps.py:152\u001b[0m, in \u001b[0;36mOptuna_XGB_Dask\u001b[1;34m(client, dtrain, n_trials, n_rounds, eval_metric, tree_method, parameter_grid, early_stopping_rounds)\u001b[0m\n\u001b[0;32m    150\u001b[0m storage \u001b[38;5;241m=\u001b[39m DaskStorage()\n\u001b[0;32m    151\u001b[0m study \u001b[38;5;241m=\u001b[39m optuna\u001b[38;5;241m.\u001b[39mcreate_study(direction\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mminimize\u001b[39m\u001b[38;5;124m\"\u001b[39m, storage\u001b[38;5;241m=\u001b[39m storage)\n\u001b[1;32m--> 152\u001b[0m \u001b[43mstudy\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43moptimize\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m    153\u001b[0m \u001b[43m    \u001b[49m\u001b[43mobjective\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\n\u001b[0;32m    154\u001b[0m \u001b[43m    \u001b[49m\u001b[43mn_trials\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mn_trials\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    155\u001b[0m \u001b[43m    \u001b[49m\u001b[43mn_jobs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m-\u001b[39;49m\u001b[38;5;241;43m1\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m  \u001b[49m\u001b[38;5;66;43;03m# Use all available cores\u001b[39;49;00m\n\u001b[0;32m    156\u001b[0m \u001b[43m    \u001b[49m\u001b[43mgc_after_trial\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m,\u001b[49m\u001b[43m  \u001b[49m\u001b[38;5;66;43;03m# Clean memory after each trial\u001b[39;49;00m\n\u001b[0;32m    157\u001b[0m \u001b[43m    \u001b[49m\u001b[43mshow_progress_bar\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\n\u001b[0;32m    158\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    160\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m study\n",
      "File \u001b[1;32mc:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\study.py:475\u001b[0m, in \u001b[0;36mStudy.optimize\u001b[1;34m(self, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)\u001b[0m\n\u001b[0;32m    373\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21moptimize\u001b[39m(\n\u001b[0;32m    374\u001b[0m     \u001b[38;5;28mself\u001b[39m,\n\u001b[0;32m    375\u001b[0m     func: ObjectiveFuncType,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    382\u001b[0m     show_progress_bar: \u001b[38;5;28mbool\u001b[39m \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mFalse\u001b[39;00m,\n\u001b[0;32m    383\u001b[0m ) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m    384\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"Optimize an objective function.\u001b[39;00m\n\u001b[0;32m    385\u001b[0m \n\u001b[0;32m    386\u001b[0m \u001b[38;5;124;03m    Optimization is done by choosing a suitable set of hyperparameter values from a given\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    473\u001b[0m \u001b[38;5;124;03m            If nested invocation of this method occurs.\u001b[39;00m\n\u001b[0;32m    474\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[1;32m--> 475\u001b[0m     \u001b[43m_optimize\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m    476\u001b[0m \u001b[43m        \u001b[49m\u001b[43mstudy\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[0;32m    477\u001b[0m \u001b[43m        \u001b[49m\u001b[43mfunc\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mfunc\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    478\u001b[0m \u001b[43m        \u001b[49m\u001b[43mn_trials\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mn_trials\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    479\u001b[0m \u001b[43m        \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtimeout\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    480\u001b[0m \u001b[43m        \u001b[49m\u001b[43mn_jobs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mn_jobs\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    481\u001b[0m \u001b[43m        \u001b[49m\u001b[43mcatch\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mtuple\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mcatch\u001b[49m\u001b[43m)\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mif\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[38;5;28;43misinstance\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mcatch\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mIterable\u001b[49m\u001b[43m)\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01melse\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43m(\u001b[49m\u001b[43mcatch\u001b[49m\u001b[43m,\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    482\u001b[0m \u001b[43m        \u001b[49m\u001b[43mcallbacks\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mcallbacks\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    483\u001b[0m \u001b[43m        \u001b[49m\u001b[43mgc_after_trial\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mgc_after_trial\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    484\u001b[0m \u001b[43m        \u001b[49m\u001b[43mshow_progress_bar\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mshow_progress_bar\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    485\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32mc:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py:100\u001b[0m, in \u001b[0;36m_optimize\u001b[1;34m(study, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)\u001b[0m\n\u001b[0;32m     98\u001b[0m                     \u001b[38;5;66;03m# Raise if exception occurred in executing the completed futures.\u001b[39;00m\n\u001b[0;32m     99\u001b[0m                     \u001b[38;5;28;01mfor\u001b[39;00m f \u001b[38;5;129;01min\u001b[39;00m completed:\n\u001b[1;32m--> 100\u001b[0m                         \u001b[43mf\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mresult\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    102\u001b[0m                 futures\u001b[38;5;241m.\u001b[39madd(\n\u001b[0;32m    103\u001b[0m                     executor\u001b[38;5;241m.\u001b[39msubmit(\n\u001b[0;32m    104\u001b[0m                         _optimize_sequential,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    115\u001b[0m                     )\n\u001b[0;32m    116\u001b[0m                 )\n\u001b[0;32m    117\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n",
      "File \u001b[1;32mc:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\concurrent\\futures\\_base.py:449\u001b[0m, in \u001b[0;36mFuture.result\u001b[1;34m(self, timeout)\u001b[0m\n\u001b[0;32m    447\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m CancelledError()\n\u001b[0;32m    448\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_state \u001b[38;5;241m==\u001b[39m FINISHED:\n\u001b[1;32m--> 449\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m__get_result\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    451\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_condition\u001b[38;5;241m.\u001b[39mwait(timeout)\n\u001b[0;32m    453\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_state \u001b[38;5;129;01min\u001b[39;00m [CANCELLED, CANCELLED_AND_NOTIFIED]:\n",
      "File \u001b[1;32mc:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\concurrent\\futures\\_base.py:401\u001b[0m, in \u001b[0;36mFuture.__get_result\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    399\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_exception:\n\u001b[0;32m    400\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 401\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_exception\n\u001b[0;32m    402\u001b[0m     \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[0;32m    403\u001b[0m         \u001b[38;5;66;03m# Break a reference cycle with the exception in self._exception\u001b[39;00m\n\u001b[0;32m    404\u001b[0m         \u001b[38;5;28mself\u001b[39m \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\concurrent\\futures\\thread.py:58\u001b[0m, in \u001b[0;36m_WorkItem.run\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m     55\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m\n\u001b[0;32m     57\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m---> 58\u001b[0m     result \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfn\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     59\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mBaseException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m exc:\n\u001b[0;32m     60\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mfuture\u001b[38;5;241m.\u001b[39mset_exception(exc)\n",
      "File \u001b[1;32mc:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py:160\u001b[0m, in \u001b[0;36m_optimize_sequential\u001b[1;34m(study, func, n_trials, timeout, catch, callbacks, gc_after_trial, reseed_sampler_rng, time_start, progress_bar)\u001b[0m\n\u001b[0;32m    157\u001b[0m         \u001b[38;5;28;01mbreak\u001b[39;00m\n\u001b[0;32m    159\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 160\u001b[0m     frozen_trial \u001b[38;5;241m=\u001b[39m \u001b[43m_run_trial\u001b[49m\u001b[43m(\u001b[49m\u001b[43mstudy\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mfunc\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mcatch\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    161\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[0;32m    162\u001b[0m     \u001b[38;5;66;03m# The following line mitigates memory problems that can be occurred in some\u001b[39;00m\n\u001b[0;32m    163\u001b[0m     \u001b[38;5;66;03m# environments (e.g., services that use computing containers such as GitHub Actions).\u001b[39;00m\n\u001b[0;32m    164\u001b[0m     \u001b[38;5;66;03m# Please refer to the following PR for further details:\u001b[39;00m\n\u001b[0;32m    165\u001b[0m     \u001b[38;5;66;03m# https://github.com/optuna/optuna/pull/325.\u001b[39;00m\n\u001b[0;32m    166\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m gc_after_trial:\n",
      "File \u001b[1;32mc:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py:248\u001b[0m, in \u001b[0;36m_run_trial\u001b[1;34m(study, func, catch)\u001b[0m\n\u001b[0;32m    241\u001b[0m         \u001b[38;5;28;01massert\u001b[39;00m \u001b[38;5;28;01mFalse\u001b[39;00m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mShould not reach.\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    243\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m (\n\u001b[0;32m    244\u001b[0m     frozen_trial\u001b[38;5;241m.\u001b[39mstate \u001b[38;5;241m==\u001b[39m TrialState\u001b[38;5;241m.\u001b[39mFAIL\n\u001b[0;32m    245\u001b[0m     \u001b[38;5;129;01mand\u001b[39;00m func_err \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[0;32m    246\u001b[0m     \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(func_err, catch)\n\u001b[0;32m    247\u001b[0m ):\n\u001b[1;32m--> 248\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m func_err\n\u001b[0;32m    249\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m frozen_trial\n",
      "File \u001b[1;32mc:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\optuna\\study\\_optimize.py:197\u001b[0m, in \u001b[0;36m_run_trial\u001b[1;34m(study, func, catch)\u001b[0m\n\u001b[0;32m    195\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m get_heartbeat_thread(trial\u001b[38;5;241m.\u001b[39m_trial_id, study\u001b[38;5;241m.\u001b[39m_storage):\n\u001b[0;32m    196\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 197\u001b[0m         value_or_values \u001b[38;5;241m=\u001b[39m \u001b[43mfunc\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtrial\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    198\u001b[0m     \u001b[38;5;28;01mexcept\u001b[39;00m exceptions\u001b[38;5;241m.\u001b[39mTrialPruned \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m    199\u001b[0m         \u001b[38;5;66;03m# TODO(mamu): Handle multi-objective cases.\u001b[39;00m\n\u001b[0;32m    200\u001b[0m         state \u001b[38;5;241m=\u001b[39m TrialState\u001b[38;5;241m.\u001b[39mPRUNED\n",
      "File \u001b[1;32mc:\\Users\\amali\\OneDrive\\Desktop\\Programming\\new_programming\\My_ML_Wraps.py:139\u001b[0m, in \u001b[0;36mOptuna_XGB_Dask.<locals>.objective\u001b[1;34m(trial)\u001b[0m\n\u001b[0;32m    136\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m: \n\u001b[0;32m    137\u001b[0m     param_grid \u001b[38;5;241m=\u001b[39m parameter_grid\n\u001b[1;32m--> 139\u001b[0m output \u001b[38;5;241m=\u001b[39m \u001b[43mdxgb\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mtrain\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m    140\u001b[0m \u001b[43m    \u001b[49m\u001b[43mclient\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    141\u001b[0m \u001b[43m    \u001b[49m\u001b[43mparam_grid\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    142\u001b[0m \u001b[43m    \u001b[49m\u001b[43mdtrain\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    143\u001b[0m \u001b[43m    \u001b[49m\u001b[43mnum_boost_round\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mn_rounds\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    144\u001b[0m \u001b[43m    \u001b[49m\u001b[43mearly_stopping_rounds\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mearly_stopping_rounds\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    145\u001b[0m \u001b[43m    \u001b[49m\u001b[43mevals\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m[\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdtrain\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mtrain\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\u001b[43m]\u001b[49m\n\u001b[0;32m    146\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    147\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m output[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mhistory\u001b[39m\u001b[38;5;124m\"\u001b[39m][\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtrain\u001b[39m\u001b[38;5;124m\"\u001b[39m][eval_metric][\u001b[38;5;241m-\u001b[39m\u001b[38;5;241m1\u001b[39m]\n",
      "File \u001b[1;32mc:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\core.py:726\u001b[0m, in \u001b[0;36mrequire_keyword_args.<locals>.throw_if.<locals>.inner_f\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m    724\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m k, arg \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mzip\u001b[39m(sig\u001b[38;5;241m.\u001b[39mparameters, args):\n\u001b[0;32m    725\u001b[0m     kwargs[k] \u001b[38;5;241m=\u001b[39m arg\n\u001b[1;32m--> 726\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfunc\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32mc:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py:1090\u001b[0m, in \u001b[0;36mtrain\u001b[1;34m(client, params, dtrain, num_boost_round, evals, obj, feval, early_stopping_rounds, xgb_model, verbose_eval, callbacks, custom_metric)\u001b[0m\n\u001b[0;32m   1088\u001b[0m client \u001b[38;5;241m=\u001b[39m _xgb_get_client(client)\n\u001b[0;32m   1089\u001b[0m args \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mlocals\u001b[39m()\n\u001b[1;32m-> 1090\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mclient\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msync\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m   1091\u001b[0m \u001b[43m    \u001b[49m\u001b[43m_train_async\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m   1092\u001b[0m \u001b[43m    \u001b[49m\u001b[43mglobal_config\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mconfig\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_config\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m   1093\u001b[0m \u001b[43m    \u001b[49m\u001b[43mdconfig\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m_get_dask_config\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m   1094\u001b[0m \u001b[43m    \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m   1095\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32mc:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py:364\u001b[0m, in \u001b[0;36mSyncMethodMixin.sync\u001b[1;34m(self, func, asynchronous, callback_timeout, *args, **kwargs)\u001b[0m\n\u001b[0;32m    362\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m future\n\u001b[0;32m    363\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m--> 364\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43msync\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m    365\u001b[0m \u001b[43m        \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mloop\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mfunc\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mcallback_timeout\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mcallback_timeout\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\n\u001b[0;32m    366\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32mc:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py:440\u001b[0m, in \u001b[0;36msync\u001b[1;34m(loop, func, callback_timeout, *args, **kwargs)\u001b[0m\n\u001b[0;32m    437\u001b[0m         wait(\u001b[38;5;241m10\u001b[39m)\n\u001b[0;32m    439\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m error \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m--> 440\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m error\n\u001b[0;32m    441\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m    442\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m result\n",
      "File \u001b[1;32mc:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\utils.py:414\u001b[0m, in \u001b[0;36msync.<locals>.f\u001b[1;34m()\u001b[0m\n\u001b[0;32m    412\u001b[0m         awaitable \u001b[38;5;241m=\u001b[39m wait_for(awaitable, timeout)\n\u001b[0;32m    413\u001b[0m     future \u001b[38;5;241m=\u001b[39m asyncio\u001b[38;5;241m.\u001b[39mensure_future(awaitable)\n\u001b[1;32m--> 414\u001b[0m     result \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01myield\u001b[39;00m future\n\u001b[0;32m    415\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m exception:\n\u001b[0;32m    416\u001b[0m     error \u001b[38;5;241m=\u001b[39m exception\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python312\\site-packages\\tornado\\gen.py:767\u001b[0m, in \u001b[0;36mRunner.run\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    765\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m    766\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 767\u001b[0m         value \u001b[38;5;241m=\u001b[39m \u001b[43mfuture\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mresult\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    768\u001b[0m     \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m    769\u001b[0m         \u001b[38;5;66;03m# Save the exception for later. It's important that\u001b[39;00m\n\u001b[0;32m    770\u001b[0m         \u001b[38;5;66;03m# gen.throw() not be called inside this try/except block\u001b[39;00m\n\u001b[0;32m    771\u001b[0m         \u001b[38;5;66;03m# because that makes sys.exc_info behave unexpectedly.\u001b[39;00m\n\u001b[0;32m    772\u001b[0m         exc: Optional[\u001b[38;5;167;01mException\u001b[39;00m] \u001b[38;5;241m=\u001b[39m e\n",
      "File \u001b[1;32mc:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py:1026\u001b[0m, in \u001b[0;36m_train_async\u001b[1;34m(client, global_config, dconfig, params, dtrain, num_boost_round, evals, obj, feval, early_stopping_rounds, verbose_eval, xgb_model, callbacks, custom_metric)\u001b[0m\n\u001b[0;32m   1023\u001b[0m     evals_name \u001b[38;5;241m=\u001b[39m []\n\u001b[0;32m   1024\u001b[0m     evals_id \u001b[38;5;241m=\u001b[39m []\n\u001b[1;32m-> 1026\u001b[0m result \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mawait\u001b[39;00m map_worker_partitions(\n\u001b[0;32m   1027\u001b[0m     client,\n\u001b[0;32m   1028\u001b[0m     dispatched_train,\n\u001b[0;32m   1029\u001b[0m     \u001b[38;5;66;03m# extra function parameters\u001b[39;00m\n\u001b[0;32m   1030\u001b[0m     params,\n\u001b[0;32m   1031\u001b[0m     _rabit_args,\n\u001b[0;32m   1032\u001b[0m     \u001b[38;5;28mid\u001b[39m(dtrain),\n\u001b[0;32m   1033\u001b[0m     evals_name,\n\u001b[0;32m   1034\u001b[0m     evals_id,\n\u001b[0;32m   1035\u001b[0m     \u001b[38;5;241m*\u001b[39m([dtrain] \u001b[38;5;241m+\u001b[39m evals_data),\n\u001b[0;32m   1036\u001b[0m     \u001b[38;5;66;03m# workers to be used for training\u001b[39;00m\n\u001b[0;32m   1037\u001b[0m     workers\u001b[38;5;241m=\u001b[39mworkers,\n\u001b[0;32m   1038\u001b[0m )\n\u001b[0;32m   1039\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m result\n",
      "File \u001b[1;32mc:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py:551\u001b[0m, in \u001b[0;36mmap_worker_partitions\u001b[1;34m(client, func, workers, *refs)\u001b[0m\n\u001b[0;32m    549\u001b[0m bag \u001b[38;5;241m=\u001b[39m db\u001b[38;5;241m.\u001b[39mfrom_delayed(futures)\n\u001b[0;32m    550\u001b[0m fut \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mawait\u001b[39;00m bag\u001b[38;5;241m.\u001b[39mreduction(first_valid, first_valid)\n\u001b[1;32m--> 551\u001b[0m result \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mawait\u001b[39;00m client\u001b[38;5;241m.\u001b[39mcompute(fut)\u001b[38;5;241m.\u001b[39mresult()\n\u001b[0;32m    553\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m result\n",
      "File \u001b[1;32mc:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\distributed\\client.py:410\u001b[0m, in \u001b[0;36mFuture._result\u001b[1;34m(self, raiseit)\u001b[0m\n\u001b[0;32m    408\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m raiseit:\n\u001b[0;32m    409\u001b[0m     typ, exc, tb \u001b[38;5;241m=\u001b[39m exc\n\u001b[1;32m--> 410\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m exc\u001b[38;5;241m.\u001b[39mwith_traceback(tb)\n\u001b[0;32m    411\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m    412\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m exc\n",
      "File \u001b[1;32mc:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py:535\u001b[0m, in \u001b[0;36m<lambda>\u001b[1;34m()\u001b[0m\n\u001b[0;32m    531\u001b[0m         \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m    532\u001b[0m             args\u001b[38;5;241m.\u001b[39mappend(ref)\n\u001b[0;32m    533\u001b[0m     fut \u001b[38;5;241m=\u001b[39m client\u001b[38;5;241m.\u001b[39msubmit(\n\u001b[0;32m    534\u001b[0m         \u001b[38;5;66;03m# turn result into a list for bag construction\u001b[39;00m\n\u001b[1;32m--> 535\u001b[0m         \u001b[38;5;28;01mlambda\u001b[39;00m \u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs: [func(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)],\n\u001b[0;32m    536\u001b[0m         \u001b[38;5;241m*\u001b[39margs,\n\u001b[0;32m    537\u001b[0m         pure\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mFalse\u001b[39;00m,\n\u001b[0;32m    538\u001b[0m         workers\u001b[38;5;241m=\u001b[39m[addr],\n\u001b[0;32m    539\u001b[0m         allow_other_workers\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mFalse\u001b[39;00m,\n\u001b[0;32m    540\u001b[0m     )\n\u001b[0;32m    541\u001b[0m     futures\u001b[38;5;241m.\u001b[39mappend(fut)\n\u001b[0;32m    543\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mfirst_valid\u001b[39m(results: Iterable[Optional[_MapRetT]]) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m Optional[_MapRetT]:\n",
      "File \u001b[1;32mc:\\Users\\amali\\miniconda3\\envs\\myenvironment\\Lib\\site-packages\\xgboost\\dask\\__init__.py:990\u001b[0m, in \u001b[0;36mdispatched_train\u001b[1;34m()\u001b[0m\n\u001b[0;32m    980\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m CommunicatorContext(\u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mrabit_args), config\u001b[38;5;241m.\u001b[39mconfig_context(\u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mglobal_config):\n\u001b[0;32m    981\u001b[0m     Xy, evals \u001b[38;5;241m=\u001b[39m _get_dmatrices(\n\u001b[0;32m    982\u001b[0m         train_ref,\n\u001b[0;32m    983\u001b[0m         train_id,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    987\u001b[0m         n_threads\u001b[38;5;241m=\u001b[39mn_threads,\n\u001b[0;32m    988\u001b[0m     )\n\u001b[1;32m--> 990\u001b[0m     booster \u001b[38;5;241m=\u001b[39m worker_train(\n\u001b[0;32m    991\u001b[0m         params\u001b[38;5;241m=\u001b[39mlocal_param,\n\u001b[0;32m    992\u001b[0m         dtrain\u001b[38;5;241m=\u001b[39mXy,\n\u001b[0;32m    993\u001b[0m         num_boost_round\u001b[38;5;241m=\u001b[39mnum_boost_round,\n\u001b[0;32m    994\u001b[0m         evals_result\u001b[38;5;241m=\u001b[39mlocal_history,\n\u001b[0;32m    995\u001b[0m         evals\u001b[38;5;241m=\u001b[39mevals \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mlen\u001b[39m(evals) \u001b[38;5;241m!=\u001b[39m \u001b[38;5;241m0\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[0;32m    996\u001b[0m         obj\u001b[38;5;241m=\u001b[39mobj,\n\u001b[0;32m    997\u001b[0m         feval\u001b[38;5;241m=\u001b[39mfeval,\n\u001b[0;32m    998\u001b[0m         custom_metric\u001b[38;5;241m=\u001b[39mcustom_metric,\n\u001b[0;32m    999\u001b[0m         early_stopping_rounds\u001b[38;5;241m=\u001b[39mearly_stopping_rounds,\n\u001b[0;32m   1000\u001b[0m         verbose_eval\u001b[38;5;241m=\u001b[39mverbose_eval,\n\u001b[0;32m   1001\u001b[0m         xgb_model\u001b[38;5;241m=\u001b[39mxgb_model,\n\u001b[0;32m   1002\u001b[0m         callbacks\u001b[38;5;241m=\u001b[39mcallbacks,\n\u001b[0;32m   1003\u001b[0m     )\n\u001b[0;32m   1004\u001b[0m \u001b[38;5;66;03m# Don't return the boosters from empty workers. It's quite difficult to\u001b[39;00m\n\u001b[0;32m   1005\u001b[0m \u001b[38;5;66;03m# guarantee everything is in sync in the present of empty workers, especially\u001b[39;00m\n\u001b[0;32m   1006\u001b[0m \u001b[38;5;66;03m# with complex objectives like quantile.\u001b[39;00m\n\u001b[0;32m   1007\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m Xy\u001b[38;5;241m.\u001b[39mnum_row() \u001b[38;5;241m!=\u001b[39m \u001b[38;5;241m0\u001b[39m:\n",
      "File \u001b[1;32m/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py:726\u001b[0m, in \u001b[0;36minner_f\u001b[1;34m()\u001b[0m\n",
      "File \u001b[1;32m/opt/coiled/env/lib/python3.12/site-packages/xgboost/training.py:176\u001b[0m, in \u001b[0;36mtrain\u001b[1;34m()\u001b[0m\n",
      "File \u001b[1;32m/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py:179\u001b[0m, in \u001b[0;36mbefore_training\u001b[1;34m()\u001b[0m\n",
      "File \u001b[1;32m/opt/coiled/env/lib/python3.12/site-packages/xgboost/callback.py:374\u001b[0m, in \u001b[0;36mbefore_training\u001b[1;34m()\u001b[0m\n",
      "File \u001b[1;32m/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py:2743\u001b[0m, in \u001b[0;36mnum_boosted_rounds\u001b[1;34m()\u001b[0m\n",
      "File \u001b[1;32m/opt/coiled/env/lib/python3.12/site-packages/xgboost/core.py:284\u001b[0m, in \u001b[0;36m_check_call\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mXGBoostError\u001b[0m: [23:53:02] /workspace/src/learner.cc:764: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?\nStack trace:\n  [bt] (0) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7f645262dcbc]\n  [bt] (1) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c2820) [0x7f64529c2820]\n  [bt] (2) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5c93fc) [0x7f64529c93fc]\n  [bt] (3) /opt/coiled/env/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x34) [0x7f6452535704]\n  [bt] (4) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x6d8a) [0x7f64f4721d8a]\n  [bt] (5) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(+0x61cd) [0x7f64f47211cd]\n  [bt] (6) /opt/coiled/env/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x7f64f472191d]\n  [bt] (7) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x9854) [0x7f64f4730854]\n  [bt] (8) /opt/coiled/env/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8bbf) [0x7f64f472fbbf]\n\n"
     ]
    }
   ],
   "source": [
    "# Dask Example:Optuna Hyperparameter Optimization and Model Training\n",
    "study= My_ML_Wraps.Optuna_XGB_Dask(client, dtrain,  n_trials=500, n_rounds=100, eval_metric= 'mape', tree_method='hist', early_stopping_rounds=20)\n",
    "final_model= dxgb.train(client, study.best_params, dtrain, num_boost_round=100, evals=[(dtrain, \"train\")])\n",
    "model_features = final_model['booster'].feature_names\n",
    "dtest= dxgb.DaskDMatrix(client, X_test[model_features])\n",
    "predictions = dxgb.predict(client, final_model, dtest)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Dask Example:Final Model Results, Evaluation, & Visualisation\n",
    "# y_test= y_test.compute()\n",
    "predictions= pd.Series(predictions.compute(), index=y_test.index)\n",
    "r2 = r2_score(y_true=y_test, y_pred=predictions)\n",
    "std = y_test.std()\n",
    "score = study.best_value\n",
    "Thresh_var = score/std \n",
    "print('Standard_Dev: '+ f'{std}')\n",
    "print(f\"Best parameters: {study.best_params}\")\n",
    "print(f\"Best MAPE: {study.best_value}\")\n",
    "print(f\"R2 Score: {r2}\")\n",
    "# print(f'Score/Std: {Thresh_var}')\n",
    "viz = pd.concat([y_test, predictions],axis=1)\n",
    "viz.columns = ['Actual', 'Predicted']\n",
    "viz.plot(figsize=(20,10))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Pandas Example 1-Pandas with Multiprocessing Distributor: \n",
    "# Raw Data, Feature Extraction & Selection, Visualization Results\n",
    "df_pandas= My_API_Wraps.CoinGecko_HSPD_Pandas(timeframe, top_coins, periods, api_key)\n",
    "EF_pandas= My_FE_Wraps.EF_Pandas_MultiprocessingDistributor(df_pandas, ParameterComplexity=0)\n",
    "SF_pandas= My_FS_Wraps.SF_Pandas_v1(EF_pandas)\n",
    "SF_pandas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Pandas Example 1-Pandas with Multiprocessing Distributor: \n",
    "# Train-Test Split, XGBoost Hyperparameter Optimization & Model Training, Evaluation, & Visualisation\n",
    "X= SF_pandas.drop('y_future', axis=1)\n",
    "y= SF_pandas['y_future']\n",
    "X_train = X.iloc[:int(-0.2*len(SF_pandas))]\n",
    "y_train = y.iloc[:int(-0.2*len(SF_pandas))]\n",
    "X_test = X.iloc[int(-0.2*len(SF_pandas)):]\n",
    "y_test = y.iloc[int(-0.2*len(SF_pandas)):]\n",
    "RGS= My_ML_Wraps.RGS_XGB_Pandas(X_train, X_test, y_train, y_test, parameter_grid=None, number_cvs=5)\n",
    "final_model= RGS.best_estimator_\n",
    "final_model= final_model.fit(X_train, y_train, eval_set=[(X_train, y_train)])\n",
    "preds=final_model.predict(X_test)\n",
    "r2= final_model.score(X_test, y_test)\n",
    "predictions = pd.DataFrame(preds, columns= ['predicted'], index= X_test.index)\n",
    "predictions['realised']= y_test.values\n",
    "predictions.plot(figsize=(20,10))\n",
    "score = RGS.best_score_\n",
    "std = y_test.std()\n",
    "print('RGS Best Score: '+ f'{score}')\n",
    "print('Y_test Standard_Dev: '+ f'{std}')\n",
    "print(f'R2: {r2}')\n",
    "feature_imp = pd.DataFrame(data = final_model.feature_importances_, index= final_model.feature_names_in_, columns=['f_imp']).sort_values(ascending=False, by='f_imp')\n",
    "Thresh_var = score/std \n",
    "print(f'score/std: {Thresh_var}')\n",
    "display(feature_imp)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Pandas Example 2-Pandas with Dask Distributor: \n",
    "# Raw Data, Feature Extraction & Selection, Visualization Results\n",
    "df_pandas2= My_API_Wraps.CoinGecko_HSPD_Pandas(timeframe, top_coins, periods, api_key)\n",
    "EF_pandas2= My_FE_Wraps.EF_Pandas_DaskDistributor(df_pandas2, cluster.scheduler_address, ParameterComplexity=0)\n",
    "SF_pandas2= My_FS_Wraps.SF_Pandas_v1(EF_pandas2)\n",
    "SF_pandas2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Pandas Example 2-Pandas with Dask Distributor: \n",
    "# Train-Test Split, XGBoost Hyperparameter Optimization & Model Training, Evaluation, & Visualisation\n",
    "X= SF_pandas2.drop('y_future', axis=1)\n",
    "y= SF_pandas2['y_future']\n",
    "X_train = X.iloc[:int(-0.2*len(SF_pandas2))]\n",
    "y_train = y.iloc[:int(-0.2*len(SF_pandas2))]\n",
    "X_test = X.iloc[int(-0.2*len(SF_pandas2)):]\n",
    "y_test = y.iloc[int(-0.2*len(SF_pandas2)):]\n",
    "RGS= My_ML_Wraps.RGS_XGB_Pandas(X_train, X_test, y_train, y_test, parameter_grid=None, number_cvs=5)\n",
    "final_model= RGS.best_estimator_\n",
    "final_model= final_model.fit(X_train, y_train, eval_set=[(X_train, y_train)])\n",
    "preds=final_model.predict(X_test)\n",
    "r2= final_model.score(X_test, y_test)\n",
    "predictions = pd.DataFrame(preds, columns= ['predicted'], index= X_test.index)\n",
    "predictions['realised']= y_test.values\n",
    "predictions.plot(figsize=(20,10))\n",
    "score = RGS.best_score_\n",
    "std = y_test.std()\n",
    "print('RGS Best Score: '+ f'{score}')\n",
    "print('Y_test Standard_Dev: '+ f'{std}')\n",
    "print(f'R2: {r2}')\n",
    "feature_imp = pd.DataFrame(data = final_model.feature_importances_, index= final_model.feature_names_in_, columns=['f_imp']).sort_values(ascending=False, by='f_imp')\n",
    "Thresh_var = score/std \n",
    "print(f'score/std: {Thresh_var}')\n",
    "display(feature_imp)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "myenvironment",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
